# Generated by Django 4.1.7 on 2023-05-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_produitnc_command'),
    ]

    operations = [
        migrations.DeleteModel(
            name='command',
        ),
    ]
